### ISSUE TITLE
CommunityDKP has not finished initialization

### ISSUE THREAD

**Issue by tpme06** [Vapok/CommunityDKP#125] opened 2020-07-31 23:43 UTC
As soon as I log on I get an error message for Community DKP but only on ONE of my two WoW accounts, despite re-installing multiple times. When I type /dkp it says it has not finished initialization and I cannot get it to load at all. I have version 3.1.3

Here is the error:
Date: 2020-07-31 19:40:11
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\CommunityDKP.lua line 196:
   attempt to compare nil with number
Debug:
   CommunityDKP\CommunityDKP.lua:196:
      CommunityDKP\CommunityDKP.lua:193
   [C]: sort()
   CommunityDKP\CommunityDKP.lua:193: SortDKPTable()
   CommunityDKP\CommunityDKP.lua:164: FilterDKPTable()
   CommunityDKP\CommunityDKP.lua:676: CreateMenu()
   CommunityDKP\init.lua:641:
      CommunityDKP\init.lua:640
Locals:
a = <table> {
 previous_dkp = 0
 dkp = 84
 class = "ROGUE"
 lifetime_gained = 200
 player = "Zro"
 version = "v3.1.0-r39"
 lifetime_spent = -51
 role = "Melee DPS"
 spec = "Combat (19/32/0)"
 rankName = "None"
 rank = 10
}
b = <table> {
 player = "Tombradygoat"
 version = "Unknown"
 class = "PALADIN"
}
(*temporary) = 84
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
button = CommDKPDKPTableHeadersSortButtonDkp {
 Id = "dkp"
 t = <unnamed> {
 }
 Ascend = true
 0 = <userdata>
}
id = "dkp"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.4
  AtlasLootClassicData, vv1.5.4
  AtlasLootClassicDungeonsAndRaids, vv1.5.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.8
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.1
  ClassicCastbars, vv1.3.9
  ClassicCastbarsOptions, v
  ClassicLootAssistant, v
  CommunityDKP, v3.1.0
  DBMCore, v1.13.54
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  FishingBuddy, v0.7.3 Beta 7
  GatherMate2, v1.45.5
  GuildRosterManager, v1.88
  honorspy, v1.7.6
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  NovaInstanceTracker, v1.11
  NovaWorldBuffs, v1.75
  OmniBar, vv10.8
  OmniCC, v8.3.5
  Questie, v6.0.4
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  TomTom, vv11305-1.1.3
  VendorPrice, v1.3.6
  WeakAuras, v2.17.12
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=73f)

**Comment by Vapok** [comment] 2020-08-02 03:47
This is now the 3rd or 4th time someone has shown me this error. It's because of a bad DKP table record that doesn't have complete information. In all examples, the offending record was a duplicate of a record, but missing the DKP fields. I have put in an automatic repair function now that will detect and cleanse. It will also report on the name of the bad entry to allow for follow-up.

This will go out in the next release.

**Closed as completed** 2020-08-02 03:47 UTC
Labels: bug
