### ISSUE TITLE
Class icons don't match class count for the histogram

### ISSUE THREAD

**Issue by jvolkenant** [Vapok/CommunityDKP#94] opened 2020-07-11 04:54 UTC
**Describe the bug**
Class histogram does not match histogram at the bottom of the /dkp side panel.  The orange 6.7% for druid used to be the first column, at some patch version the icon's stayed the same, but the number's shuffled.

1) Addon Version and Release e.g. 3.1.1-r47
2) What are your DKP Modes? (screenshot preferred) omitted, but can add if needed
3) What is the issue you're seeing (screenshot preferred)
Class icon's don't match the class count
![image](https://user-images.githubusercontent.com/10521453/87216801-dedda600-c2f7-11ea-8fc6-d14b97e3050c.png)

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

**To Reproduce**
1. type /dkp
2. Click the > icon

**Expected behavior**
Class color, class count, class % and Icon shoudl match

**CommunityDKP Version**
3.1.1-r47

**Comment by Vapok** [comment] 2020-07-11 04:58
Yep, the problem is reproduced.  Looking into it.

**Comment by Vapok** [comment] 2020-07-11 05:21
Fixed in r43

**Closed as completed by Vapok** 2020-07-11 05:21 UTC
Labels: bug
